### ISSUE TITLE
Return the Features Scores

### ISSUE THREAD

**Issue by viniciusmsousa** [smazzanti/mrmr#11]
I think it would be nice to return the features scores. Or have it as optional parameter.

**Comment by smazzanti** [comment]
Sorry for the delay on this. I've just added an additional parameter called return_scores (default to false), which returns the computed relevance and redundancy.

**Comment by saskra** [comment]
Thanks for this great package and this special feature! Is it also possible to additionally return the final score used for sorting? I would like to make the number of features actually used dependent on a threshold on this score. Or is there a simple formula so that I can calculate this using redundancy and relevance?

**Comment by seymatakir** [comment]
Did you find any formula so that I can calculate this using redundancy and relevance?

**Comment by chk094** [comment]
> Did you find any formula to calculate this using redundancy and relevance?

according to the original mRMR author, the final score for MID is calculated by max(V-W), where W is redundance and V is relevance.
It is be max(v/W) for MIQ scheme.

https://home.penglab.com/proj/mRMR/BIBM07_mRMR_071103_handout.pdf
