### ISSUE TITLE
Possible error in docstring mrmr_classif (pandas)

### ISSUE THREAD

**Issue by GliozzoJ** [smazzanti/mrmr#15]
Hello,

I think there is an imprecision in the docstring of the function "mrmr_classif" present in the file pandas.py.
The docstring says:

    cat_features: list (optional, default=None)
        List of categorical features. If None, all string columns will be encoded.

but from the code I see that the function that performs the encoding (i.e.  encode_df) is called only if cat_features is provided. I do not see a point in the code where strings columns are automatically encoded (maybe I am missing something).

All the  best,

**Comment by smazzanti** [comment]
Hi,

this behaviour is inherited by the classes of category_encoders (see for example https://contrib.scikit-learn.org/category_encoders/leaveoneout.html) which are used by the function.
However, I have corrected the function because I have just noticed that the default was an empty list instead of None, as it's declared in the docstring.

Thank you,
Samuele
